server:
  port: 8080
  servlet:
    context-path: /api/v1
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:koiveterian}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    # driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:your_email@gmail.com}
    password: ${MAIL_PASSWORD:your_email_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    springdoc:
      api-docs:
        path: /api-docs
      swagger-ui:
        path: /swagger-ui.html
        operationsSorter: method
payment:
  vnPay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmnCode: ${VNPAY_TMN_CODE:12345678}
    secretKey: ${VNPAY_SECRET_KEY:1234567890}
    returnUrl: ${VNPAY_RETURN_HOST:http://localhost:8080}/api/v1/payment/vnpayback
    version: 2.1.0
    command: pay
    orderType: other
