on:
  push:
    branches: ["main"]

jobs:
  koi-api-build:
    name: Build source code to Docker image
    runs-on: ubuntu-22.04
    env:
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
    steps:
      - name: Checkout Develop
        uses: actions/checkout@v3
      - name: DockerHub Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}
      - name: Build Image And Push
        run: docker compose build api && docker compose push api

  koi-api-deploy:
    name: Deploy KOI API
    runs-on: mint-server
    needs: koi-api-build
    env:
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
    steps:
      - name: Checkout Develop
        uses: actions/checkout@v3
      - name: DockerHub Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Stop API
        run: docker compose -f docker-compose.prod.yaml -p koi-application down api --rmi all -v
        continue-on-error: true
      - name: Deploy API
        run: docker compose -f docker-compose.prod.yaml -p koi-application up -d
